modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"

[[mods]]
modId = "litematica"
version = "${version}"
displayName = "Litematica-Forge"
displayURL="https://github.com/ThinkingStudios/Litematica-Forge" #optional
logoFile="assets/litematica/icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Litematica unofficial forge port.

A modern schematic mod for Forge.
'''

[[dependencies.litematica]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.litematica]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
